function row(){
    var data=document.getElementById("input")
        var p=document.createElement("tr")
        var h=document.createElement("td")
        var btn=document.createElement("button")
        var btntext=document.createTextNode("Delete")
        btn.setAttribute("onclick","deletee(this)")
        btn.appendChild(btntext)
        var del=document.createElement("button")
        var deltext=document.createTextNode("Edit")
        del.setAttribute("onclick","edit(this)")
        del.appendChild(deltext)
        p.appendChild(h)
        p.appendChild(btn)
        p.appendChild(del)
        var node=document.createTextNode(data.value)
        h.appendChild(node)
        var show=document.getElementById("showdata")
        show.appendChild(p)
        console.log(p)

    console.log(p)
    return(
        row1(),
        row2(),
        row3()
    )
    function row1(){
        var data=document.getElementById("input1")
        var p=document.createElement("tr")
        var h=document.createElement("td")
        var btn=document.createElement("button")
        var btntext=document.createTextNode("Delete")
        btn.setAttribute("onclick","deletee(this)")
        btn.appendChild(btntext)
        var del=document.createElement("button")
        var deltext=document.createTextNode("Edit")
        del.setAttribute("onclick","edit(this)")
        del.appendChild(deltext)
        p.appendChild(h)
        p.appendChild(btn)
        p.appendChild(del)
        var node=document.createTextNode(data.value)
        h.appendChild(node)
        var show=document.getElementById("showdata")
        show.appendChild(p)
        console.log(p)
    }
    function row2(){
        var data=document.getElementById("input2")
        var p=document.createElement("tr")
        var h=document.createElement("td")
        var btn=document.createElement("button")
        var btntext=document.createTextNode("Delete")
        btn.setAttribute("onclick","deletee(this)")
        btn.appendChild(btntext)
        var del=document.createElement("button")
        var deltext=document.createTextNode("Edit")
        del.setAttribute("onclick","edit(this)")
        del.appendChild(deltext)
        p.appendChild(h)
        p.appendChild(btn)
        p.appendChild(del)
        var node=document.createTextNode(data.value)
        h.appendChild(node)
        var show=document.getElementById("showdata")
        show.appendChild(p)
        console.log(p)
    }
    function row3(){
        var data=document.getElementById("input3")
        var p=document.createElement("tr")
        var h=document.createElement("td")
        var btn=document.createElement("button")
        var btntext=document.createTextNode("Delete")
        btn.setAttribute("onclick","deletee(this)")
        btn.appendChild(btntext)
        var del=document.createElement("button")
        var deltext=document.createTextNode("Edit")
        del.setAttribute("onclick","edit(this)")
        del.appendChild(deltext)
        p.appendChild(h)
        p.appendChild(btn)
        p.appendChild(del)
        var node=document.createTextNode(data.value)
        h.appendChild(node)
        var show=document.getElementById("showdata")
        show.appendChild(p)
        console.log(p)
    }
    
}
function deletee(e){
    e.parentElement.remove()
}

